# Generated by Django 2.1 on 2018-09-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GS_Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advisor', models.TextField()),
                ('fund', models.TextField()),
                ('base_currency', models.TextField(max_length=3)),
                ('currency', models.TextField(max_length=25)),
                ('opening_balance', models.FloatField()),
                ('forwards', models.TextField()),
                ('product_description', models.TextField(max_length=254)),
                ('product_id', models.TextField(max_length=25)),
                ('activity', models.TextField(max_length=254)),
                ('account_type', models.IntegerField(max_length=3)),
                ('tradeQuantity', models.FloatField()),
                ('tradePrice', models.FloatField()),
                ('commInt', models.FloatField(max_length=254)),
                ('netAmt', models.FloatField(max_length=254)),
                ('brokerDesc', models.TextField()),
                ('accNo', models.IntegerField()),
                ('ref_no', models.TextField(max_length=254)),
            ],
        ),
    ]
