# Generated by Django 2.1 on 2018-09-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_gs_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gs_transactions',
            name='account_type',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='gs_transactions',
            name='commInt',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='gs_transactions',
            name='netAmt',
            field=models.FloatField(),
        ),
    ]
