# Generated by Django 2.1 on 2018-09-02 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_auto_20180902_1916'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GS_Transactions',
            new_name='GS_Trans',
        ),
    ]
