# Generated by Django 2.1 on 2018-09-02 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_auto_20180902_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='gs_tran',
            name='settleDate',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='gs_tran',
            name='tradeDate',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='gs_tran',
            name='product_id',
            field=models.TextField(max_length=254),
        ),
    ]
