# Generated by Django 2.1 on 2018-09-02 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_auto_20180902_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gs_tran',
            name='accNo',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gs_tran',
            name='account_type',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gs_tran',
            name='activity',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='gs_tran',
            name='advisor',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='gs_tran',
            name='base_currency',
            field=models.TextField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='gs_tran',
            name='brokerDesc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='gs_tran',
            name='commInt',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='gs_tran',
            name='currency',
            field=models.TextField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='gs_tran',
            name='forwards',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='gs_tran',
            name='fund',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='gs_tran',
            name='netAmt',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='gs_tran',
            name='opening_balance',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='gs_tran',
            name='product_description',
            field=models.TextField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='gs_tran',
            name='product_id',
            field=models.TextField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='gs_tran',
            name='ref_no',
            field=models.TextField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='gs_tran',
            name='settleDate',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='gs_tran',
            name='tradeDate',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='gs_tran',
            name='tradePrice',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='gs_tran',
            name='tradeQuantity',
            field=models.FloatField(null=True),
        ),
    ]
