# Generated by Django 2.1 on 2018-09-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_auto_20180902_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tradar_Tran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade', models.IntegerField()),
                ('fund', models.TextField()),
                ('type', models.TextField()),
                ('amount', models.FloatField(null=True)),
                ('security_type', models.TextField()),
                ('ticker', models.TextField()),
                ('isin', models.TextField(max_length=254, null=True)),
                ('cusip', models.TextField(max_length=254, null=True)),
                ('sedol', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('price', models.FloatField(null=True)),
                ('trans_date', models.TextField(null=True)),
                ('ccy', models.TextField(null=True)),
                ('settles', models.TextField(null=True)),
                ('account', models.TextField(null=True)),
                ('cashflow', models.FloatField(null=True)),
                ('balance', models.FloatField(null=True)),
            ],
        ),
    ]
