# Generated by Django 2.1 on 2018-09-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_tradar_tran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradar_tran',
            name='amount',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tradar_tran',
            name='balance',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tradar_tran',
            name='cashflow',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tradar_tran',
            name='price',
            field=models.TextField(null=True),
        ),
    ]
