# Generated by Django 2.1 on 2018-09-03 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_auto_20180903_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSB_Trans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund', models.TextField(null=True)),
                ('ticker', models.TextField(null=True)),
                ('isin', models.TextField(null=True)),
                ('sedol', models.TextField(null=True)),
                ('ss_asset_id', models.TextField(null=True)),
                ('other_id', models.TextField(null=True)),
                ('transaction', models.TextField(max_length=254, null=True)),
                ('transaction_id', models.TextField(max_length=254, null=True)),
                ('transaction_no', models.TextField(null=True)),
                ('transaction_description', models.TextField(null=True)),
                ('cash_type', models.TextField(null=True)),
                ('fx_type', models.TextField(null=True)),
                ('investment_type_code', models.IntegerField(null=True)),
                ('share_quantity', models.FloatField(null=True)),
                ('net_amt', models.FloatField(null=True)),
                ('actual_net_amt', models.FloatField(null=True)),
                ('settle_loc', models.TextField(null=True)),
                ('ss_trans_type', models.TextField(null=True)),
                ('time_stamp', models.TextField(null=True)),
                ('pay_settle_date', models.TextField(null=True)),
                ('executing_broker', models.TextField(null=True)),
                ('currency', models.TextField(null=True)),
                ('action_type', models.TextField(null=True)),
                ('security_name', models.TextField(null=True)),
                ('ss_status', models.TextField(null=True)),
                ('ss_trade_id', models.TextField(null=True)),
                ('trade_record_date', models.TextField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tradar_tran',
            name='amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tradar_tran',
            name='balance',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tradar_tran',
            name='cashflow',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tradar_tran',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
