# Generated by Django 2.1 on 2018-09-03 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0010_auto_20180903_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSB_Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund', models.TextField(null=True)),
                ('currency', models.TextField(null=True)),
                ('amount', models.FloatField(null=True)),
                ('fund_internal', models.TextField(null=True)),
            ],
        ),
    ]
