# Generated by Django 2.1 on 2018-09-04 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0012_gs_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tradar_Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.TextField(null=True)),
                ('field2', models.TextField(null=True)),
                ('field3', models.TextField(null=True)),
                ('trade', models.TextField(null=True)),
                ('type', models.TextField(null=True)),
                ('amount', models.TextField(null=True)),
                ('security', models.TextField(null=True)),
                ('isin', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('price', models.FloatField(null=True)),
                ('date', models.FloatField(null=True)),
                ('settles', models.TextField(null=True)),
                ('cashflow', models.FloatField(null=True)),
                ('balance', models.FloatField(null=True)),
            ],
        ),
    ]
