# Generated by Django 2.1 on 2018-09-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0013_tradar_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradar_balance',
            name='ticker',
            field=models.TextField(null=True),
        ),
    ]
