# Generated by Django 2.1 on 2018-09-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0014_tradar_balance_ticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradar_balance',
            name='bal',
            field=models.FloatField(null=True),
        ),
    ]
