# Generated by Django 2.1 on 2018-09-04 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0015_tradar_balance_bal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradar_balance',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='tradar_balance',
            name='bal',
        ),
        migrations.RemoveField(
            model_name='tradar_balance',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='tradar_balance',
            name='cashflow',
        ),
        migrations.RemoveField(
            model_name='tradar_balance',
            name='date',
        ),
        migrations.RemoveField(
            model_name='tradar_balance',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tradar_balance',
            name='field2',
        ),
        migrations.RemoveField(
            model_name='tradar_balance',
            name='field3',
        ),
        migrations.RemoveField(
            model_name='tradar_balance',
            name='isin',
        ),
        migrations.RemoveField(
            model_name='tradar_balance',
            name='price',
        ),
        migrations.RemoveField(
            model_name='tradar_balance',
            name='security',
        ),
        migrations.RemoveField(
            model_name='tradar_balance',
            name='settles',
        ),
        migrations.RemoveField(
            model_name='tradar_balance',
            name='ticker',
        ),
        migrations.RemoveField(
            model_name='tradar_balance',
            name='trade',
        ),
        migrations.RemoveField(
            model_name='tradar_balance',
            name='type',
        ),
    ]
