# Generated by Django 2.1 on 2018-09-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0016_auto_20180904_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradar_balance',
            name='amount',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tradar_balance',
            name='balance',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='tradar_balance',
            name='cashflow',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='tradar_balance',
            name='date',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='tradar_balance',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tradar_balance',
            name='field2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tradar_balance',
            name='field3',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tradar_balance',
            name='isin',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tradar_balance',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='tradar_balance',
            name='security',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tradar_balance',
            name='settles',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tradar_balance',
            name='ticker',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tradar_balance',
            name='trade',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tradar_balance',
            name='type',
            field=models.TextField(null=True),
        ),
    ]
